### ISSUE TITLE
Empty output: ['', '', '']

### ISSUE THREAD

**Issue by Deevad** [linuxwacom/gsetwacom#20]
Hi, 

I'm testing the Huion Kamvas Pro 19 connected to a computer with a fresh install of Fedora 40 Gnome (on Wayland) to complete my future article and offer a DIY way to use the tablet on Wayland. 

By default, the stylus can moves the cursor accross the two displays (the one of the laptop, and the one of the tablet), meaning the mapping is on both screen. 

I tempted a `sudo dnf install udev-hid-bpf`, and this action didn't fix it, but it did fix the buttons of the stylus. They are now set correctly (I can access to a right click on the second button).

Also, the tablet isn't appearing in the GNOME System Settings, under the tablet section. 

That's how I had the idea to visit this repo and install it: in the hope to control the mapping and put it back to the Huion display. So I installed it via pip as mentioned on the README. 

It works, I can run it, but I have a big issue: I can't map it to the Huion built-in monitor because the output are all empty strings. 

See:

```
deevad@fedora:~$ gsetwacom list-tablets
devices:
- name: "HUION Huion Tablet_GT1902 Pen"
  usbid: "256C:006B"
  settings:
    area: [0.0, 0.0, 0.0, 0.0]
    keep-aspect: false
    left-handed: false
    mapping: 'absolute'
    output: ['', '', '']
```
and 
```
deevad@fedora:~$ gsetwacom tablet "256C:006B" show
settings:
  area: [0.0, 0.0, 0.0, 0.0]
  keep-aspect: false
  left-handed: false
  mapping: 'absolute'
  output: ['', '', '']
```

So, I can't execute something like on the README example:
```
gsetwacom tablet "256C:006B" map-to-monitor --connector DP-1
```

**Comment by Deevad** [comment]
Workaround I found:

Go to the GNOME System Settings, under the Displays, and note the name of the display. I have here two:
1. Built-in display
2. HAT

then use this keyword along with the "vendor" name:
```
gsetwacom tablet "256C:006B" map-to-monitor --vendor HAT
```

(note: because the digitizer resolution is a square in w and h, it's necessary to turn off keep-aspect `gsetwacom tablet "256C:006B" set-keep-aspect false`)

**Comment by Deevad** [comment]
Observation:

Once set, prompting "show" again list everything:
```
deevad@fedora:~$ gsetwacom tablet "256C:006B" show
settings:
  area: [0.0, 0.0, 0.0, 0.0]
  keep-aspect: false
  left-handed: false
  mapping: 'absolute'
  output: ['HAT', 'Kamvas Pro 19', '0xf0000005', 'HDMI-1']
```
